### ISSUE TITLE
undefined reference to json_*

### ISSUE THREAD

**Issue by jhunken** [drotiro/boxfs2#13]
I was interested in testing this out, but am unable to compile it in Ubuntu 14.04. It seems to have issues with libjson. I was using `make static`. Here's the relevant output:

```
Building  boxfs
cc -D_FILE_OFFSET_BITS=64 -I/usr/local/include -I/usr/include/fuse -I/usr/include/libxml2     -o boxfs boxfs.o boxapi.o boxpath.o boxhttp.o boxopts.o boxjson.o boxcache.o boxutils.o -pthread -L/usr/local/lib -lfuse -lxml2 -lcurl -lapp -ljson   -lpthread
boxjson.o: In function `jobj_parse':
boxjson.c:(.text+0x3c7): undefined reference to `json_parser_dom_init'
boxjson.c:(.text+0x3fa): undefined reference to `json_parser_dom_callback'
boxjson.c:(.text+0x402): undefined reference to `json_parser_init'
boxjson.c:(.text+0x441): undefined reference to `json_parser_string'
boxjson.c:(.text+0x45c): undefined reference to `json_parser_is_done'
boxjson.c:(.text+0x47a): undefined reference to `json_parser_free'
boxjson.c:(.text+0x489): undefined reference to `json_parser_dom_free'
collect2: error: ld returned 1 exit status
make: *** [boxfs] Error 1
```

Full log here:
http://pastebin.com/m8RvbwGU

Any assistance would be appreciated.

**Comment by drotiro** [comment]
Hi,
looking at the log it seems that
- the static build went fine, but "make install" failed because the install target depends on "boxfs" (the dynamic build)
- the dynamic build fails because libjson is not installed

You can just:
- run boxfs from the build dir or copy it by hand somewhere in your path
- install the prerequisites and do a dynamic build

Regrads,
Domenico
