### ISSUE TITLE
rsync not working properly

### ISSUE THREAD

**Issue by lockheed** [drotiro/boxfs2#15]
I noticed that when running rsync, it behaves as regular copy-over instead of running a diff. Also, when it finishes, timestams are not preserved because 

rsync: failed to set times on "/mnt/box/.20130918_191811.jpg.7mnBxP": No such file or directory (2)

Filenames change after they are done copying and rsync does not keep track of them on boxfs. Is this something to remedy or is it just the charm of boxfs?

**Comment by drotiro** [comment]
Hi,
that error is probably caused by the way FUSE handles file close:
_"FUSE's "release" operation is called asynchronously when a file is closed from userspace. This means that, if a program writes a file, closes it, and immediately re-opens it, it might not succeed"_

Here you can find more details: http://sourceforge.net/p/fuse/mailman/fuse-devel/thread/87wslu4dq9.fsf@frosties.localdomain/
