### ISSUE TITLE
Make -o option, or make ~/.boxfs/conf the default config file.

### ISSUE THREAD

**Issue by stephensrmmartin** [drotiro/boxfs2#16]
Currently, boxfs2 does not take an -o option.
-o should take long options (e.g., conffile=/home/user/.boxfs/conf).

This is important if you want people to mount via fuse.
E.g.,
mount -t fuse boxfs ~/Box -o conffile=/home/user/Box
Why would you want to mount via fuse?
Users may need to mount this via fstab, or through systemd mount units.

Currently, this is possible with davfs. boxfs needs this option.

The primary issue is that you cannot use boxfs with mount.fuse because boxfs (for some unknown reason) does not, by default, use ~/.boxfs/conf as its configuration file, even though boxfs-init creates this file.  So you /have/ to specify -f each time you want to mount. This is fine from CLI, but for mount.fuse, you need to be able to pass it the conf option somehow, and this should be done via -o.

**Comment by drotiro** [comment]
Hi,
at the moment you can do automatic mount at boot time running boxfs instead of mount.fuse.
It may not work anyway sometimes, because the oauth tokens may be expired.

I agree, it would be useful to have a default value for -f .
The "unknown" reason is simply that in my little spare time I work on the features I need myself or like to implement.

Feel free to send some pull request if you want to contribute.

Regards.
